version: '3.9'

# list of containers
services:
  # django api server
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app/src
    depends_on:
      - postgres
    links:
      - postgres

  # postgresql database
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    # ports:
    #   - "${DB_PORT}:5432"
    # expose: 
    #   - "${DB_PORT}"
    volumes:
      - "${DB_VOLUME}:/var/lib/postgresql/data"
    env_file: 
      - .env
