version: '3.9'

# list of containers
services:
  # django api server
  backend:
    image: backend
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  # postgresql database
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    volumes:
      - "${DB_VOLUME}:/var/lib/postgresql/data"
    env_file: 
      - .env
