version: '3.9'

# list of containers
services:
  # django api server
  backend:
    image: "${BACKEND_IMG}"
    container_name: backend
    entrypoint:  ["bash", "docker-entrypoint.sh"]
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  # postgresql database
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: 
      - .env